name: primary-replica
container:
  port: 5432
  name:
    primary: primary
    replica: replica
credentials:
  primary: password
  root: password
  user: password
serviceType: ClusterIP
image:
  repository: crunchydata
  container: crunchy-postgres
  tag: centos7-11.11-4.5.2
pv:
  storage: 400M
  name: primary-pv
  mode: ReadWriteMany
  path: /data
pvc:
  name: primary-pvc
resources:
  cpu: 200m
  memory: 512Mi
